## Bank Loan Classification

In [1]:
# Import Libraries

# Standard libraries
import pandas as pd

# Custom class libraries
import random_forest_custom

In [2]:
# Read dataset
input_file_path = '/Users/test/Documents/git_workspace/bank_loan_classification/UniversalBank.csv'
input_data = pd.read_csv(input_file_path)

In [3]:
# Get insights on the data
# input_data.head(10)
# input_data.shape[1]
input_data.describe()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,93152.503000,2.396400,1.937938,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852197,1.147663,1.747659,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [5]:
# Create a class object
class_obj = random_forest_custom.RandomForest()
X_train, X_test, y_train, y_test = class_obj.data_preparation(input_data, 0.7)

In [6]:
# Train model
model = class_obj.train_model(20, X_train, y_train)

In [7]:
# Predict results
y_pred = class_obj.predict_results(model, X_test)

In [8]:
# Evaluate results

# 1. Accuracy score
accuracy_score = class_obj.evaluate_results(y_test, y_pred)
print(accuracy_score)

0.7168571428571429